
package view;

import controller.ControleDevedores;
import controller.IControleDevedores;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Devedor;

public class ListarDevedores extends javax.swing.JInternalFrame {
    
    private String user;
    private IControleDevedores controle = new ControleDevedores();
    private JDesktopPane d;
    
    public ListarDevedores(String user, JDesktopPane d) {
        initComponents();
        this.user = user;
        this.d = d;
    }

    private String getUser() {
        return user;
    }

    private IControleDevedores getControle() {
        return controle;
    }

    public JDesktopPane getD() {
        return d;
    }
    
    
//    public void setControle(IControleDevedores controle) {
//        this.controle = controle;
//    }

    public void setUser(String user) {
        this.user = user;
    }
    private void read(){
         DefaultTableModel modelo = (DefaultTableModel) this.tabela.getModel();
         modelo.setNumRows(0); //eliminar duplicadas do java 
         
         for (Devedor d: this.getControle().listarDevedores(this.getUser())){
             //terminar
         }
         
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Devedores");
        setMaximumSize(new java.awt.Dimension(694, 517));
        setMinimumSize(new java.awt.Dimension(694, 517));
        setPreferredSize(new java.awt.Dimension(694, 517));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "Telefone", "Numero de dividas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jButton1.setText("Delatar Devedor");

        jToggleButton1.setText("Criar Divida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
