
package view;

import controller.ControleDevedores;
import controller.ControleLogin;
import controller.IControleDevedores;
import controller.IControleLogin;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Devedor;
import model.bean.Usuario;

public class ListarDevedores extends javax.swing.JInternalFrame {
    
    private String user;
    private IControleDevedores controle = new ControleDevedores();
    private JDesktopPane d;
    private String nomeDevedor;
    
    public ListarDevedores(String user, JDesktopPane d) {
        initComponents();
        this.user = user;
        this.d = d;
        this.read();
        this.destivarBotoes();
    }

    private String getUser() {
        return user;
    }

    private IControleDevedores getControle() {
        return controle;
    }

    public JDesktopPane getD() {
        return d;
    }

    private String getNomeDevedor() {
        return nomeDevedor;
    }

    private void setNomeDevedor(String nomeDevedor) {
        this.nomeDevedor = nomeDevedor;
    }
    
    
//    public void setControle(IControleDevedores controle) {
//        this.controle = controle;
//    }

    public void setUser(String user) {
        this.user = user;
    }
    private void read(){
        
        //falta tocar o id pelo numero de dividas, em resumo pegar todas as dividas de determinado devedor
         DefaultTableModel modelo = (DefaultTableModel) this.tabelaDevedores.getModel();
         modelo.setNumRows(0); //eliminar duplicadas do java 
         
         for (Devedor d: this.getControle().listarDevedores(this.getUser())){
             //terminar
             modelo.addRow(new Object[]{
                 d.getNome(),
                 d.getCidade(),
                 d.getTelefone1(),
                 d.getId()
             });
         } 
    }
    
    private void ativarBotoes(){
        this.btnAtualizarDevedor.setEnabled(true); 
        this.btnCriarDivida.setEnabled(true);
        this.btnDeletarDevedor.setEnabled(true); 
        this.btninformacoesDevedor.setEnabled(true);
        this.btnverDividasDevedor.setEnabled(true);
    }
    private void destivarBotoes(){
        this.btnAtualizarDevedor.disable(); //desativar botão atualizar devedor
        this.btnCriarDivida.disable(); //desativa botao de criar divida
        this.btnDeletarDevedor.disable(); //destaiva botao de deletarDevedor
        this.btninformacoesDevedor.disable();
        this.btnverDividasDevedor.disable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDevedores = new javax.swing.JTable();
        btnDeletarDevedor = new javax.swing.JButton();
        btnAtualizarDevedor = new javax.swing.JButton();
        btninformacoesDevedor = new javax.swing.JButton();
        btnverDividasDevedor = new javax.swing.JButton();
        btnCriarDivida = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Devedores");
        setMaximumSize(new java.awt.Dimension(694, 517));
        setMinimumSize(new java.awt.Dimension(694, 517));
        setPreferredSize(new java.awt.Dimension(694, 517));

        tabelaDevedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "Telefone", "Numero de dividas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDevedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDevedoresMouseClicked(evt);
            }
        });
        tabelaDevedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaDevedoresKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDevedores);

        btnDeletarDevedor.setText("Delatar Devedor");
        btnDeletarDevedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarDevedorActionPerformed(evt);
            }
        });

        btnAtualizarDevedor.setText("Atualizar Devedor");

        btninformacoesDevedor.setText("Informações completas");

        btnverDividasDevedor.setText("Ver Dividas");

        btnCriarDivida.setText("Criar Divida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeletarDevedor)
                    .addComponent(btnCriarDivida))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnverDividasDevedor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtualizarDevedor)
                        .addGap(26, 26, 26)
                        .addComponent(btninformacoesDevedor)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletarDevedor)
                    .addComponent(btnAtualizarDevedor)
                    .addComponent(btninformacoesDevedor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnverDividasDevedor)
                    .addComponent(btnCriarDivida))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaDevedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaDevedoresKeyPressed
        this.ativarBotoes();
        if (this.tabelaDevedores.getSelectedRow() != -1) {
            this.setNomeDevedor(this.tabelaDevedores.getValueAt(this.tabelaDevedores.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaDevedoresKeyPressed

    private void tabelaDevedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDevedoresMouseClicked
        this.ativarBotoes();
        if (this.tabelaDevedores.getSelectedRow() != -1) {
            this.setNomeDevedor(this.tabelaDevedores.getValueAt(this.tabelaDevedores.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_tabelaDevedoresMouseClicked

    private void btnDeletarDevedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarDevedorActionPerformed
        IControleLogin contr1 = new ControleLogin();
        Usuario user = contr1.buscaUser(this.getUser());
        IControleDevedores contr2 = new ControleDevedores();
        Devedor selecionado = contr2.buscaDedevor(user, this.getNomeDevedor());
        
    }//GEN-LAST:event_btnDeletarDevedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarDevedor;
    private javax.swing.JButton btnCriarDivida;
    private javax.swing.JButton btnDeletarDevedor;
    private javax.swing.JButton btninformacoesDevedor;
    private javax.swing.JButton btnverDividasDevedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDevedores;
    // End of variables declaration//GEN-END:variables
}
